# Generated by Django 4.1.3 on 2022-11-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyservicemodel',
            name='phoneNumber',
            field=models.CharField(max_length=16, verbose_name='Номер телефона'),
        ),
    ]
