# Generated by Django 4.1.3 on 2022-11-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appealmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealmodel',
            name='services',
            field=models.ManyToManyField(related_name='services', to='core.emergencyservicemodel'),
        ),
    ]
