# Generated by Django 4.1.3 on 2022-11-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_services_appealmodel_servicesrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appealmodel',
            name='servicesRelation',
        ),
        migrations.AddField(
            model_name='appealmodel',
            name='services',
            field=models.ManyToManyField(to='core.emergencyservicemodel'),
        ),
    ]
