# Generated by Django 4.1.3 on 2022-11-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_appealmodel_servicesrelation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantmodel',
            name='birthDate',
            field=models.DateField(default="1900-01-01", verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appealmodel',
            name='services',
            field=models.ManyToManyField(blank=True, to='core.emergencyservicemodel'),
        ),
    ]
