# Generated by Django 4.1.3 on 2022-11-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_applicantmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantmodel',
            name='health_state',
            field=models.TextField(blank=True, default='практически здоров', verbose_name='Состояние здоровья'),
        ),
        migrations.AlterField(
            model_name='applicantmodel',
            name='phone_number',
            field=models.BigIntegerField(blank=True, verbose_name='Номер телефона'),
        ),
    ]
