# Generated by Django 4.1.3 on 2022-11-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_applicantmodel_health_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
