# Generated by Django 4.1.3 on 2022-11-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_applicantmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
