# Generated by Django 4.1.3 on 2022-11-02 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_appealmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 15, 23, 35, 520893), verbose_name='Дата'),
        ),
    ]
