# Generated by Django 4.1.3 on 2022-11-02 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_appealmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер карточки')),
                ('injured_count', models.PositiveIntegerField(verbose_name='Количество пострадавших')),
                ('dont_call', models.BooleanField(verbose_name='Не звонить')),
            ],
        ),
        migrations.AlterField(
            model_name='appealmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 15, 42, 24, 856966), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='appealmodel',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='emergencyservicemodel',
            name='service_code',
            field=models.PositiveIntegerField(verbose_name='Код службы'),
        ),
    ]
