# Generated by Django 4.1.3 on 2022-11-02 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_accidentmodel_alter_appealmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accidentmodel',
            options={'verbose_name': 'Происшествие', 'verbose_name_plural': 'Происшествия'},
        ),
        migrations.AlterField(
            model_name='appealmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 15, 46, 30, 477861), verbose_name='Дата'),
        ),
    ]
