# Generated by Django 4.1.3 on 2022-11-02 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_accidentmodel_options_alter_appealmodel_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accidentmodel',
            old_name='number',
            new_name='card_number',
        ),
        migrations.AlterField(
            model_name='appealmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 17, 26, 10, 792818), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='applicantmodel',
            name='health_state',
            field=models.TextField(blank=True, default='практически здоров', help_text='аллергоанамнез, хронические заболевания и т.п.', verbose_name='Состояние здоровья'),
        ),
    ]
