# Generated by Django 4.1.3 on 2022-11-02 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_number_accidentmodel_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 18, 9, 34, 267456), verbose_name='Дата'),
        ),
        migrations.AddIndex(
            model_name='accidentmodel',
            index=models.Index(fields=['card_number'], name='core_accide_card_nu_ad4d6a_idx'),
        ),
    ]
