# Generated by Django 4.1.3 on 2022-11-02 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_appealmodel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealmodel',
            name='status',
            field=models.CharField(choices=[('В работе', 'In Progress'), ('Завершено', 'Done')], default='В работе', max_length=16),
        ),
        migrations.AlterField(
            model_name='appealmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 19, 46, 4, 632972), verbose_name='Дата'),
        ),
    ]
