# Generated by Django 4.1.3 on 2022-11-02 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_accidentmodel_core_accide_card_nu_ad4d6a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentmodel',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='appealmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 20, 10, 41, 702958), verbose_name='Дата'),
        ),
    ]
