# Generated by Django 4.1.3 on 2022-11-02 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_accidentmodel_number_alter_appealmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealmodel',
            name='card_number',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True, verbose_name='Номер карточки'),
        ),
        migrations.AlterField(
            model_name='appealmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 20, 23, 58, 206184), verbose_name='Дата'),
        ),
    ]
