# Generated by Django 4.1.3 on 2022-11-02 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_appealmodel_card_number_alter_appealmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
    ]
