# Generated by Django 4.1.3 on 2022-11-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_appealmodel_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantmodel',
            options={'ordering': ['surname', 'first_name', 'patronymic_name'], 'verbose_name': 'Заявитель', 'verbose_name_plural': 'Заявители'},
        ),
        migrations.AddField(
            model_name='applicantmodel',
            name='first_name',
            field=models.CharField(max_length=40, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='applicantmodel',
            name='patronymic_name',
            field=models.CharField(max_length=40, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='applicantmodel',
            name='surname',
            field=models.CharField(max_length=40, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='appealmodel',
            name='status',
            field=models.CharField(choices=[('В работе', 'In Progress'), ('Завершено', 'Done')], default='В работе', max_length=16, verbose_name='Статус'),
        ),

        # User-defined operations to preserve old data
        migrations.RenameField(
            model_name='emergencyservicemodel',
            old_name='service_code',
            new_name='service_code_old',
        ),
        migrations.AddField(
            model_name='emergencyservicemodel',
            name='service_code',
            field=models.CharField(max_length=16, verbose_name='Код службы', null=True),
        ),


    ]
