# Generated by Django 4.1.3 on 2022-11-03 07:47

from django.db import migrations


def prepend_zero_to_service_code(apps, schema_editor):
    model = apps.get_model("core", "EmergencyServiceModel")
    for item in model.objects.all():
        item.service_code = '0' + str(item.service_code_old)
        item.save()


def split_names(apps, schema_editor):
    model = apps.get_model("core", "ApplicantModel")
    for item in model.objects.all():
        names = item.full_name.split(' ')
        item.surname, item.first_name, item.patronymic_name = names
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_applicantmodel_options_and_more'),
    ]

    operations = [
        migrations.RunPython(prepend_zero_to_service_code),
        migrations.RunPython(split_names),
    ]
