# Generated by Django 4.1.3 on 2022-11-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_post23_data_saving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantmodel',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='emergencyservicemodel',
            name='service_code_old',
        ),
        migrations.AlterField(
            model_name='emergencyservicemodel',
            name='service_code',
            field=models.CharField(max_length=16, verbose_name='Код службы'),
        ),
    ]
