# Generated by Django 4.1.3 on 2022-11-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_post24_data_deletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantmodel',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
    ]
