# Generated by Django 4.1.3 on 2022-11-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_accidentmodel_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentmodel',
            name='additionDateTime',
            field=models.DateTimeField(null=True, verbose_name='Дата добавления'),
        ),
    ]
