# Generated by Django 4.1.3 on 2022-11-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_appealmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantmodel',
            name='accidents',
            field=models.ManyToManyField(blank=True, to='core.accidentmodel'),
        ),
        migrations.AlterField(
            model_name='appealmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
