# Generated by Django 4.1.3 on 2022-11-10 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_appealmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealmodel',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='core.applicantmodel', verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='appealmodel',
            name='services',
            field=models.ManyToManyField(blank=True, to='core.emergencyservicemodel', verbose_name='Задействованные службы'),
        ),
    ]
