# Generated by Django 4.1.3 on 2022-11-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_appealmodel_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealmodel',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='applicantmodel',
            name='accidents',
            field=models.ManyToManyField(blank=True, to='core.accidentmodel', verbose_name='Происшествия'),
        ),
        migrations.AlterField(
            model_name='applicantmodel',
            name='first_name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='applicantmodel',
            name='patronymic_name',
            field=models.CharField(default='', max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='applicantmodel',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='applicantmodel',
            name='surname',
            field=models.CharField(default='', max_length=255, verbose_name='Фамилия'),
        ),
    ]
