# Generated by Django 4.1.3 on 2022-11-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_appealmodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantmodel',
            name='accidents',
        ),
        migrations.AddField(
            model_name='appealmodel',
            name='dont_call',
            field=models.BooleanField(default=False, verbose_name='Не звонить'),
        ),
        migrations.AddField(
            model_name='appealmodel',
            name='injured_count',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество пострадавших'),
        ),
        migrations.DeleteModel(
            name='AccidentModel',
        ),
    ]
